version: '2'
services:
  composeapi:
    build: ../foDocker/foDocker-compose-api
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - 3000
    restart: always
    command: perl compose_api.pl daemon
  watcher:
    build: ../foDocker/foDocker-watcher
    ports:
      - 3000
    restart: always
    environment:
      MOJO_EVENTEMITTER_DEBUG: 0
    command: perl watcher.pl daemon
    depends_on:
      - composeapi
      - mongo
  mongo:
    image: mongo
  influxdb:
    image: tutum/influxdb:latest
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      ADMIN_USER: root
      INFLUXDB_INIT_PWD: 12345
      PRE_CREATE_DB: fodocker
  graphana:
    image: grafana/grafana
    ports:
      - 8082:3000
  metric_writer:
    build: .
    image: sample
    command: ./test.sh
